spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.chitchato.com/realms/chitchato/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
  datasource:
    url: jdbc:mysql://localhost:3306/chitchato_backend
    username: root
    password: P@55w0rd
  jpa:
    show-sql: true